# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peerbeam < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/6b70/peerbeam/releases/download/v0.0.1/peerbeam_Darwin_x86_64.tar.gz"
      sha256 "8cc300a41c6e841250acb7a20bd42a29d671834078d2cf1d8c46811aede24ebb"

      def install
        bin.install "peerbeam"
      end
    end
    on_arm do
      url "https://github.com/6b70/peerbeam/releases/download/v0.0.1/peerbeam_Darwin_arm64.tar.gz"
      sha256 "ad87e962c4e0fb24c38e84cb379c81c183089ae84f4186744f05ccaf43cfc7d6"

      def install
        bin.install "peerbeam"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/6b70/peerbeam/releases/download/v0.0.1/peerbeam_Linux_x86_64.tar.gz"
        sha256 "4b7f71a2ffec351947e5ee5f930e6d59047f1d69104e483506c5b7a52d6e9ca3"

        def install
          bin.install "peerbeam"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/6b70/peerbeam/releases/download/v0.0.1/peerbeam_Linux_arm64.tar.gz"
        sha256 "68306ecf84053a5fa1ebf56b8d119e48b884a7de8fb92c67fbab45099b9df183"

        def install
          bin.install "peerbeam"
        end
      end
    end
  end
end
